### ISSUE TITLE
Missing PNG files

### ISSUE THREAD

**Issue by crshrprt** [EemilAhonen/leikkaus#1]
Thank you for this interesting plugin.

I was trying to build it on Linux, however there are 2 missing files, as shown in Projucer:

![leikkaus](https://github.com/EemilAhonen/leikkaus/assets/114294020/47ce2640-b1ae-4bb6-9cc2-38fd3cae0024)

**Comment by EemilAhonen** [comment]
Hello! Neither of them are used in the code, they are just placeholders for me while I'm working on the UI, I removed them from the .jucer file and will keep anything local out of there.

**Comment by crshrprt** [comment]
Now it builds fine, thank you.
